ecomapp/urls.py
from django.urls import path
from .views import *

app_name = 'ecomapp'
urlpatterns = [
    # clients
    path('', ClientHomeView.as_view(), name="clienthome"),
    path('product/<int:pk>/productdetail',
         ClientProductDetailView.as_view(), name="clientproductdetail"),
    path('review-<pro_id>/', ClientReviewView.as_view(), name="clientreview"),
    path('review-<pro_id>/<int:pk>/delete-productreview',
         ClientReviewDeleteView.as_view(), name="clientreviewdelete"),
    path('my-cart/', MyCartView.as_view(), name="mycart"),
    path('add-to-cart/', AddToCartView.as_view(), name="addtocart"),
    path('manage-cart/', ManageCartView.as_view(), name="managecart"),

    path('checkout/', OrderCreateView.as_view(), name="ordercreate"),
    # Customer Registration
    path('register/', RegistrationView.as_view(), name="registration"),

    # admin
    path('ecom-admin/', AdminHomeView.as_view(), name="adminhome"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('ecom-admin/product/',
         AdminProductView.as_view(), name="adminproduct"),
    path('ecom-admin/order-<int:pk>/',
         AdminOrderDetailView.as_view(), name="adminorderdetail"),


    # API Views
    path('api/product/list-create/',
         ApiProductLCView.as_view(), name="apiproductlc"),
    path('api/product-<int:pk>/',
         ApiProductRUDView.as_view(), name="apiproductrud")

]

ecomproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ecomapp.urls')),
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/clienttemplates/addtocart.html
{{product.title}} added to cart successfully.

templates/clienttemplates/clientbase.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
	{% block css %}

	{% endblock %}
	<style type="text/css">
		.subcat{
			list-style: none;
		}
        hr{
        	border-bottom: 1px solid red;
        }
        .allcat{
        	border-bottom:  1px solid red;
        }
	
	</style>
</head>
<body class="container-fluid">

	<div class="row">
		<div class="col-md-3">
		 <nav class="navbar navbar-sm bg-light">
		<h4 class="allcat">All Categories</h4>
			<ul class="navbar-nav">
				<li class="nav-item">
					<a class="nav-link" href="{% url 'ecomapp:clienthome' %}">All Products</a>
				</li>
				{% for category in allcategorys %}
				<li class="nav-item">
					<a class="nav-link" href="/?cat={{category.slug}}">{{category.title}}</a>
				</li>
				{% for subcategory in category.productcategory_set.all %}
				<li class="ml-3 subcat">
					<a href="/?cat={{subcategory.slug}}">{{subcategory.title}}</a>
				</li>
				{% endfor %}
				{% endfor %}
			</ul>
		 </nav>	
		</div>
		<div class="col-md-9">
		 <nav class="navbar navbar-expand-sm bg-light">	
			<ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/"><span style="color: green">Kinmel.com</span></a>
              </li>
             
              <li class="nav-item">
                <a class="nav-link float-right" href="{% url 'ecomapp:mycart' %}">Cart</a>
              </li>
               	{% if request.user.is_authenticated and request.user.groups.first.name == "customer" %}
               <li class="nav-item">
                <a class="nav-link text-success" href="#">{{request.user}}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/logout">Logout</a>
              </li>
                {% else %}
              <li class="nav-item">
                <a href="/login/" class="nav-link">Login</a>
              	
              </li>
              <li class="nav-item">
              	
                <a href="/register/" class="nav-link">Register</a>
              </li>
                {% endif %}
            </ul>
         </nav>   
           
<br>



			{% block content %}

			{% endblock %}
		
	</div>

<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script type="text/javascript" src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

{% block js %}
{% endblock %}
</body>
</html>

templates/clienttemplates/clienthome.html
{% extends 'clienttemplates/clientbase.html' %}

{% load static %}

{% block content %}

<style type="text/css">
	.add-to-cart {
		color: yellow;
	}
</style>
<h3>{{thiscat}}</h3><hr>
<div class="row">
	{% for product in allproducts %}
	<div class=" col-md-3 mt-3">
		<div class="card" >
			<img class="card-img-top" src="{{product.image.url}}" alt="img-fluid img-thumbnail" style="height: 250px;object-fit: cover;">
			<div class="card-body">
				<h5 class="card-title"><a href="{% url 'ecomapp:clientproductdetail' product.id%}">{{product.title}}</h5></a>
				<p class="card-text" style="font-size: 12px;">Price: <strike>Rs {{product.mrp}}</strike> Rs. {{product.sp}} </p>
				<p>Discount: {{product.discount}}%</p>
				<p class="card-text" style="font-size: 12px;">Quantity: {{product.quantity}} </p>
				<a href="{% url 'ecomapp:addtocart' %}?p_id={{product.id}}" class="btn btn-primary add-to-cart">Add to cart</a>
			</div>
		</div>
	</div>
	{% endfor %}
</div>
{% for subcat in thiscat.productcategory_set.all %}
<hr>
<h4 class="text-info" >{{subcat.title}}</h4>
<div class="row">
	{% for product in subcat.product_set.all %}
	<div class=" col-md-3">
		<div class="card" >
			<img class="card-img-top" src="{{product.image.url}}" alt="img-fluid img-thumbnail" style="height: 250px;object-fit: cover;">
			<div class="card-body">
				<h5 class="card-title"><a href="{% url 'ecomapp:clientproductdetail' product.id%}">{{product.title}}</h5></a>
				<p class="card-text" style="font-size: 12px;">Price: <strike>Rs {{product.mrp}}</strike> Rs. {{product.sp}} </p>
				<p>Discount: {{product.discount}}%</p>
				<p class="card-text" style="font-size: 12px;">Quantity: {{product.quantity}} </p>

				<a href="{% url 'ecomapp:addtocart' %}?p_id={{product.id}}" class="btn btn-primary add-to-cart">Add to cart</a>
			</div>
		</div>
	</div>
	{% endfor %}
</div>
{% endfor %}

{% endblock %}

{% block js %}
<script type="text/javascript">
	$(document).ready(function(){
		$('.add-to-cart').on('click', function(e){
			e.preventDefault();
			$.ajax({
				url: $(this).attr('href'),
				data: {},
				success: function(data){
					alert(data)
				}
			})
		})
	})
</script>
{% endblock %}

templates/clienttemplates/clientproductdetail.html
{% extends 'clienttemplates/clientbase.html' %}

{% load static %}

{% block content %}
<style type="text/css">
	h5{
		margin-bottom: 15px;
	}
</style>
<h3>{{thiscat}}</h3><hr>
		 <h4><span style="color:blue;font-weight:bold">{{productdetail.title}}</span></h4><hr>
<div class="row">
	<div class="col-md-4">
		 <img src="{{productdetail.image.url}}" class="img-fluid"><br><br>
		
	</div>
	<div class="col-md-4">
		<h5><span style="color:blue;font-weight:bold;">Title</span>: {{productdetail.title}}</h5>
		<h5><span style="color:blue;font-weight:bold;">Category</span>: {{productdetail.category}}</h5>
		<h5><span style="color:blue;font-weight:bold;">Sku</span>: {{productdetail.sku}}</h5>
		<h5><span style="color:blue;font-weight:bold;">Mrp</span>: {{productdetail.mrp}}</h5>
		<h5><span style="color:blue;font-weight:bold;">Sp</span>: {{productdetail.sp}}</h5>
		<h5><span style="color:blue;font-weight:bold;">Quantity</span>: {{productdetail.quantity}}</h5>
		
	</div>
	<div class="col-md-4 bg-success text-white p-3">
		<h3>Delivery Options</h3><hr>
		<p>Free Delivery inside kathmandu valley. </p>
		<p>Rs. 200/-  outside kathmandu valley. </p><hr>
		<p class="text-warning">Rs. 250 off for every purchage greater than Rs 2500</p>
		{% if request.user.is_authenticated and request.user.groups.first.name == "customer" %}
		<form method="POST" action="{% url 'ecomapp:clientreview' productdetail.pk %}">
			{% csrf_token %}
			{{reviewform.as_p}}
			<button class="btn btn-info">Give review</button>
		</form>
		{% else %}
			<a href="/login/">Login to review</a>
		{% endif %}
	</div>
	<div class="col-md-12">
		<p><span style="color:blue;font-weight:bold">Description</span>: {{productdetail.description}}</p>
	</div>


</div>
<div class="row">
	<div class="col-md-12">
		<h4 class="p-1 text-warning">Customer reviews on this product</h4><hr>
		{% for review in productdetail.productreview_set.all|dictsortreversed:"id" %}
		<div class="row">
			<div class="col-md-8">
				<li>{{review.review}}</li>
				<p class="{% if review.rating == 'Excellent' %}text-success{% elif review.rating == 'Good' or review.rating == 'Average' %}text-info{% elif review.rating == 'Poor' %}text-warning{% else %}text-danger{% endif %}">({{review.rating}}) 
					{% if review.customer == request.user.customer %}
					<a href="{% url 'ecomapp:clientreviewdelete' productdetail.id review.id %}"><span class="fa fa-trash"></span></a>
					{% endif %}

				</p>

			</div>
			<div class="col-md-4">
				<li>Review by: {{review.customer.name}}</li>
				<p>on: {{review.created_at}}</p>
			</div>
				

			

		</div>
		{% endfor %}
	</div>
</div>

{% endblock %}			

templates/clienttemplates/clientreviewdelete.html
<form method="POST">
	{% csrf_token %}
	<button>Delete</button>
</form>

templates/clienttemplates/errorpage.html
{{errordescription}}

templates/clienttemplates/managecart.html
{{message}}

templates/clienttemplates/mycart.html
{% extends 'clienttemplates/clientbase.html' %}


{% block title %}My cart{% endblock %}

{% block css %}

{% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-12" id="mytable-wrapper">
		<h3>My Cart</h3>
		<table class="table table-bordered mytable">
			<thead>
				<tr>
					<th>SN</th>
					<th>Product</th>
					<th>Price</th>
					<th>Quantity</th>
					<th>Subtotal</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
				{% for cartproduct in cart.cartproduct_set.all %}
				<tr>
					<td>{{forloop.counter}}</td>
					<td>{{cartproduct.product.title}}</td>
					<td>{{cartproduct.rate}}</td>
					<td>{{cartproduct.quantity}}</td>
					<td>{{cartproduct.subtotal}}</td>
					<td>
						<a class="btn btn-success manage-cart" href="{% url 'ecomapp:managecart' %}?action=inc&cp_id={{cartproduct.id}}"><i class="fa fa-plus"></i></a>
						<a class="btn btn-warning manage-cart" href="{% url 'ecomapp:managecart' %}?action=dec&cp_id={{cartproduct.id}}"><i class="fa fa-minus"></i></a>
						<a class="btn btn-danger manage-cart" href="{% url 'ecomapp:managecart' %}?action=del&cp_id={{cartproduct.id}}"><i class="fa fa-trash"></i></a>
					</td>
				</tr>

				{% empty %}
				<tr>
					<td colspan="4" class="text-center">-- No items in the cart --<br><a href="/">Continue shopping</a></td>
					
				</tr>
				{% endfor %}
				<tr>
					<th colspan="4" class="text-right">Total</th>
					<th>{{cart.total}}</th>
					<th><a class="manage-cart" href="{% url 'ecomapp:managecart' %}?action=empty&c_id={{cart.id}}">Empty Cart</a></th>
				</tr>
			</tbody>
		</table>
			{% if cart.cartproduct_set.count > 0 %}<a href="{% url 'ecomapp:ordercreate' %}">Checkout</a>{% endif %}
	</div>
</div>
{% endblock %}

{% block js %}
<script type="text/javascript">
	$('#mytable-wrapper').on('click', '.manage-cart',function(e){
		e.preventDefault();
		$.ajax({
			url: $(this).attr('href'),
			data: {},
			success: function(data){
				alert(data);
				$('#mytable-wrapper').load('#mytable-wrapper .mytable')
			}
		})

	})
</script>
{% endblock %}

templates/clienttemplates/ordercreate.html
{% extends 'clienttemplates/clientbase.html' %}

{% load static %}

{% block content %}
<h3>{{thiscat}}</h3><hr>
<div class="row">
	<div class="col-md-6">
		<h4>Shipping Information</h4>
		<form method="POST">
			{% csrf_token %}
			{{form.as_p}}
			<button>Place order</button>
		</form>
	</div>
	<div class="col-md-6">
		<h3>Cart Information</h3><hr>
		{% for cartproduct in cart.cartproduct_set.all %}
		<li>{{cartproduct.product.title}}(Rs. {{cartproduct.rate}} * {{cartproduct.quantity}}) = Rs. {{cartproduct.subtotal}}</li>
		{% endfor %}
		<hr>
		<li style="list-style: none; margin-left: 40%;">Total: Rs. {{cart.total}} /-</li>
	</div>

</div>
{% endblock %}

templates/clienttemplates/registration.html
{% extends 'clienttemplates/clientbase.html' %}

{% load static %}

{% block content %}
<style type="text/css">

    form{
        border: 1px solid blue!important;
        padding: 15px;
        margin: 5px;
    }
    #id_username{
        color: red;
    }
    #form-wrapper{

    }
</style>
<div class="row">
        <div class="col-md-6 mx-auto">
            <!-- main-heading -->
            <h2>Registration form</h2>
                
        	{% if error %}
            <li class="text-danger">{{error}}</li>
            {% endif %}
            <form method="POST" enctype="multipart/form-data">
             {% csrf_token %}
             {{ form.as_p }}
             <button class="btn btn-info w-75 primary">Login</button>

            </form>	
		</div>
</div>


{% endblock %}