ecomapp/urls.py
from django.urls import path
from .views import *

app_name = 'ecomapp'
urlpatterns = [
    # clients
    path('', ClientHomeView.as_view(), name="clienthome"),
    path('product/<int:pk>/productdetail',
         ClientProductDetailView.as_view(), name="clientproductdetail"),
    path('review-<pro_id>/', ClientReviewView.as_view(), name="clientreview"),
    path('review-<pro_id>/<int:pk>/delete-productreview',
         ClientReviewDeleteView.as_view(), name="clientreviewdelete"),
    path('my-cart/', MyCartView.as_view(), name="mycart"),
    path('add-to-cart/', AddToCartView.as_view(), name="addtocart"),
    path('manage-cart/', ManageCartView.as_view(), name="managecart"),

    path('checkout/', OrderCreateView.as_view(), name="ordercreate"),
    # Customer Registration
    path('register/', RegistrationView.as_view(), name="registration"),

    # admin
    path('ecom-admin/', AdminHomeView.as_view(), name="adminhome"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('ecom-admin/product/',
         AdminProductView.as_view(), name="adminproduct"),
    path('ecom-admin/order-<int:pk>/',
         AdminOrderDetailView.as_view(), name="adminorderdetail"),


    # API Views
    path('api/product/list-create/',
         ApiProductLCView.as_view(), name="apiproductlc"),
    path('api/product-<int:pk>/',
         ApiProductRUDView.as_view(), name="apiproductrud")

]

ecomproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ecomapp.urls')),
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/admintemplates/adminbase.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body class="container">

	<a href="/ecom-admin/">Admin Home</a>
	<a href="{% url 'ecomapp:adminproduct' %}">View Product </a>

    <a href="">{{request.user}}</a>
  

 {% block content %}
 
 {% endblock %}


	<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script type="text/javascript" src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>


{% block js %}

{% endblock %}
</body>
</html>

templates/admintemplates/adminhome.html
{% extends 'admintemplates/adminbase.html' %}

{% load static %}

{% block content %}


<div class="row">
	<div class="col-md-8">
		<h3>Latest Order</h3>
		<table class="table">
			<thead>
				<tr>
					<th>SN</th>
					<th>Order Id</th>
					<th>Cart Id</th>
					<th>Customer</th>
					<th>Shipping Address</th>
					<th>Total</th>
					<th>Ordered on</th>
				</tr>
			</thead>
			<tbody>
				{% for order in orderlist %}
				<tr>
					<td>{{forloop.counter}}</td>
					<td><a href="/ecom-admin/order-{{order.id}}/">#ORDER_{{order.id}}</a></td>
					<td>#CART_{{order.cart.id}}</td>
					<td>{{order.cart.customer}}<br>({{order.mobile}})</td>
					<td>{{order.municipality}}<br>({{order.street_address}})</td>
					<td>{{order.total}}</td>
					<td>{{order.created_at}}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>
{% endblock %}

templates/admintemplates/adminlogin.html
{% extends 'clienttemplates/clientbase.html' %}

{% block content %}
<style type="text/css">
    form{
        border: 1px solid blue!important;
        padding: 15px;
    }
    #id_username{
        color: red;
    }
    #form-wrapper{

    }
</style>
	<h3>Login Form</h3>
	{% if error %}
    <li class="text-danger">{{error}}</li>
    {% endif %}
    <form method="POST">
     {% csrf_token %}
     {{ form.as_p }}
     <button class="btn btn-info w-75 primary">Login</button>

    </form>	
{% endblock %}

templates/admintemplates/adminorderdetail.html
{% extends 'admintemplates/adminbase.html' %}

{% block content %}
<div class="row">
	<div class="col-md-6">
		<h3>Customer Information</h3>
		<table class="table table-bordered">
			<tr>
				<th>Customer</th>
				<td>{{orderobj.cart.customer}}</td>
			</tr>
			<tr>
				<th>Shipping Address</th>
				<td>{{orderobj.municipality}}<br>({{orderobj.street_address}})</td>
			</tr>
		</table>
	</div>
	<div class="col-md-6">
		<h3>Ordered Products Information</h3>
		<table class="table table-striped">
			<thead>
				<tr>
					<th>SN</th>
					<th>Product</th>
					<th>Rate</th>
					<th>Quantity</th>
					<th>Subtotal</th>
				</tr>
			</thead>
			<tbody>
				{% for product in orderobj.cart.cartproduct_set.all %}
				<tr>
					<td>{{forloop.counter}}</td>
					<td>{{product.product.title}}</td>
					<td>{{product.rate}}</td>
					<td>{{product.quantity}}</td>
					<td>{{product.subtotal}}</td>
				</tr>
				{% endfor %}
				<tr>
					<th>Total</th>
					<th>{{orderobj.total}}</th>
				</tr>
			</tbody>
		</table>
	</div>
</div>
{% endblock %}

templates/admintemplates/adminproduct.html
{% extends 'admintemplates/adminbase.html' %}

{% block content %}
<div class="row">
	<div class="col-md-12">
		<h3>All Products</h3>
		<select id="category">
			<option value="all">All Category</option>
			{% for category in allcategorys %}
			<option value="{{category.id}}">{{category.title}}</option>
			{% endfor %}
		</select>
		<table class="table table-striped">
			<thead>
				<tr>
					<th>SN</th>
					<th>Title</th>
					<th>Sku</th>
					<th>Category</th>
					<th>mrp</th>
					<th>sp</th>
				</tr>
			</thead>
			<tbody>
				{% for category in allcategories %}
				<tr class="bg-dark text-white"><td colspan="6">Category: {{category.title}}</td></tr>
				{% for product in category.product_set.all %}
				<tr>
					<td>{{forloop.counter}}</td>
					<td>{{product.title}}</td>
					<td>{{product.sku}}</td>
					<td>{{product.category}}</td>
					<td>{{product.mrp}}</td>
					<td>{{product.sp}}</td>
				</tr>
				{% empty %}
				<tr><td colspan="6">No products available in this category</td></tr>
				{% endfor %}
				{% endfor %}

			</tbody>
			<hr>
				
		</table>
	</div>
</div>
			
				


			


{% endblock %}

{% block js %}
<script>
	$(document).ready(function(){
		var params = new window.URLSearchParams(window.location.search);

		$('#category').val(params.get('category'));
		
		$('#category').change(function(){
			var value = $(this).val();
			window.location.href = "{% url 'ecomapp:adminproduct' %}" + "?category=" + value;
		})
	})
</script>
{% endblock %}